### ISSUE TITLE
About releasing the pre-trained model and the music dataset?

### ISSUE THREAD

**Issue by shiyanpei0826** [RetroCirce/MusicLDM#7]
Hi

   This is a wonderful project! 

   Could you please tell us that is there any plan to release the pre-trained model file and the music dataset used in this project?

   Thank you.

**Comment by RetroCirce** [comment]
Hi, the pretrained model has been released.
The dataset we trained is actually in our previous repo of CLAP (search AudioStock): https://github.com/LAION-AI/audio-dataset/blob/main/laion-audio-630k/README.md
